### ISSUE TITLE
[post list] Crash opening a post

### ISSUE THREAD

**Issue by NicKoehler** [diegoberaldin/RaccoonForLemmy#940]
**Describe the bug**
Opening a specific post crash the app.

**To Reproduce**
1. Open [this post](https://programming.dev/post/15150291)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Version 1.11.1

**Additional context**

```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240505.005/2024060500:user/release-keys
package: com.github.diegoberaldin.raccoonforlemmy.android:104
process: com.github.diegoberaldin.raccoonforlemmy.android
processUptime: 8940 + 238 ms
installer: dev.imranr.obtainium

java.lang.IllegalStateException: Nothing to pop.
	at C0.c.e(Unknown Source:39)
	at android.support.v4.media.session.b.c(Unknown Source:68)
	at g4.f.u(Unknown Source:172)
	at W.d.f(Unknown Source:43)
	at W.d.u(Unknown Source:8)
	at O9.l.v(Unknown Source:484)
	at K7.d.o(Unknown Source:844)
	at W.d.o(Unknown Source:51)
	at A0.u.t(Unknown Source:4)
	at O.p.b(Unknown Source:145)
	at O9.l.b(Unknown Source:602)
	at g4.e.o(Unknown Source:661)
	at W.d.o(Unknown Source:51)
	at A0.u.t(Unknown Source:4)
	at O.p.b(Unknown Source:145)
	at S3.e.c(Unknown Source:735)
	at S3.e.f(Unknown Source:1107)
	at b4.I0.o(Unknown Source:121)
	at W.d.o(Unknown Source:51)
	at D6.b.o(Unknown Source:428)
	at W.d.o(Unknown Source:51)
	at A0.u.t(Unknown Source:4)
	at O.p.a(Unknown Source:217)
	at S3.b.b(Unknown Source:160)
	at S9.c.j(Unknown Source:1204)
	at S9.c.o(Unknown Source:1934)
	at K6.g0.k(Unknown Source:604)
	at W.d.b(Unknown Source:43)
	at W.d.k(Unknown Source:8)
	at F.V.u(Unknown Source:61)
	at W.d.f(Unknown Source:43)
	at W.d.u(Unknown Source:8)
	at D.Y.o(Unknown Source:88)
	at W.d.o(Unknown Source:51)
	at A0.u.t(Unknown Source:4)
	at O.p.a(Unknown Source:217)
	at z.E.a(Unknown Source:180)
	at y.j.a(Unknown Source:32)
	at D.j.o(Unknown Source:39)
	at W.d.o(Unknown Source:51)
	at A0.u.t(Unknown Source:4)
	at O.p.a(Unknown Source:217)
	at X.h.f(Unknown Source:95)
	at z.P.f(Unknown Source:20)
	at z.x.b(Unknown Source:104)
	at F.x.o(Unknown Source:189)
	at W.d.o(Unknown Source:51)
	at F.x.o(Unknown Source:452)
	at W.d.o(Unknown Source:51)
	at O.p.F(Unknown Source:14)
	at O.o.r(Unknown Source:121)
	at O.o.k(Unknown Source:10)
	at O.t.k(Unknown Source:35)
	at O.q0.a(Unknown Source:44)
	at O.m.a(Unknown Source:4)
	at O.m.a(Unknown Source:4)
	at O.m.a(Unknown Source:4)
	at O.t.l(Unknown Source:8)
	at s0.E.i(Unknown Source:21)
	at s0.E.h(Unknown Source:118)
	at s0.z.P(Unknown Source:170)
	at y.l.a(Unknown Source:51)
	at y.m.o(Unknown Source:1020)
	at F.x.o(Unknown Source:82)
	at s0.B.c(Unknown Source:77)
	at u0.t.b(Unknown Source:37)
	at u.k.k(Unknown Source:13)
	at s0.v.h(Unknown Source:7)
	at u0.y.b(Unknown Source:10)
	at u.k.k(Unknown Source:53)
	at s0.v.h(Unknown Source:7)
	at u0.y.b(Unknown Source:10)
	at g0.K.h(Unknown Source:0)
	at u0.y.b(Unknown Source:10)
	at x.B.h(Unknown Source:96)
	at u0.y.b(Unknown Source:10)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.I.b(Unknown Source:95)
	at x.s.c(Unknown Source:214)
	at u0.t.b(Unknown Source:37)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.I.b(Unknown Source:95)
	at x.c0.b(Unknown Source:115)
	at x.b0.c(Unknown Source:31)
	at u0.t.b(Unknown Source:37)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.I.b(Unknown Source:95)
	at x.s.c(Unknown Source:82)
	at u0.t.b(Unknown Source:37)
	at x.B.h(Unknown Source:96)
	at u0.y.b(Unknown Source:10)
	at x.T.h(Unknown Source:32)
	at u0.y.b(Unknown Source:10)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.I.b(Unknown Source:95)
	at M.P1.o(Unknown Source:905)
	at s0.B.c(Unknown Source:77)
	at u0.t.b(Unknown Source:37)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.P.d(Unknown Source:54)
	at u0.P.l(Unknown Source:123)
	at u0.P.f(Unknown Source:120)
	at u0.P.e(Unknown Source:42)
	at v0.s.m(Unknown Source:2)
	at u0.I.D0(Unknown Source:54)
	at u0.I.b(Unknown Source:95)
	at s.m.c(Unknown Source:23)
	at u0.t.b(Unknown Source:37)
	at s.A.h(Unknown Source:226)
	at u0.y.b(Unknown Source:10)
	at g0.K.h(Unknown Source:0)
	at u0.y.b(Unknown Source:10)
	at D.X0.k(Unknown Source:268)
	at s0.v.h(Unknown Source:7)
	at u0.y.b(Unknown Source:10)
	at androidx.lifecycle.L.d(Unknown Source:1169)
	at Y.s.d(Unknown Source:59)
	at Y.v.a(Unknown Source:51)
	at Y.w.c(Unknown Source:152)
	at u0.e0.a(Unknown Source:2)
	at u0.I.D0(Unknown Source:128)
	at u0.P.d(Unknown Source:54)
	at u0.P.l(Unknown Source:123)
	at u0.P.i(Unknown Source:86)
	at v0.s.u(Unknown Source:35)
	at v0.s.dispatchDraw(Unknown Source:14)
	at android.view.View.draw(View.java:24193)
	at android.view.View.updateDisplayListIfDirty(View.java:23056)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5234)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4900)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4049)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:938)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by diegoberaldin** [comment]
Yes I can reproduce it too, here is the unobfuscated stack trace

```
 java.lang.IllegalStateException: Nothing to pop.
	at androidx.compose.ui.text.AnnotatedString$Builder.pop(AnnotatedString.kt:610)
	at com.mikepenz.markdown.compose.elements.MarkdownParagraphKt.MarkdownParagraph(MarkdownParagraph.kt:21)
	at com.github.diegoberaldin.raccoonforlemmy.core.markdown.CustomMarkdownWrapperKt$CustomMarkdownWrapper$components$1.invoke(CustomMarkdownWrapper.kt:112)
	at com.github.diegoberaldin.raccoonforlemmy.core.markdown.CustomMarkdownWrapperKt$CustomMarkdownWrapper$components$1.invoke(CustomMarkdownWrapper.kt:90)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at com.mikepenz.markdown.compose.MarkdownKt.handleElement(Markdown.kt:115)
	at com.mikepenz.markdown.compose.MarkdownKt.access$handleElement(Markdown.kt:1)
	at com.mikepenz.markdown.compose.MarkdownKt$Markdown$1.invoke(Markdown.kt:78)
	at com.mikepenz.markdown.compose.MarkdownKt$Markdown$1.invoke(Markdown.kt:74)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at com.mikepenz.markdown.compose.MarkdownKt.Markdown(Markdown.kt:65)
	at com.github.diegoberaldin.raccoonforlemmy.core.markdown.CustomMarkdownWrapperKt$CustomMarkdownWrapper$1.invoke(CustomMarkdownWrapper.kt:137)
	at com.github.diegoberaldin.raccoonforlemmy.core.markdown.CustomMarkdownWrapperKt$CustomMarkdownWrapper$1.invoke(CustomMarkdownWrapper.kt:136)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at com.github.diegoberaldin.raccoonforlemmy.core.markdown.CustomMarkdownWrapperKt.CustomMarkdownWrapper(CustomMarkdownWrapper.kt:129)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.lemmyui.PostCardBodyKt.PostCardBody(PostCardBody.kt:55)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.lemmyui.PostCardKt$ExtendedPost$2$9.invoke(PostCard.kt:602)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.lemmyui.PostCardKt$ExtendedPost$2$9.invoke(PostCard.kt:601)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.components.CustomizedContentKt$CustomizedContent$1.invoke(CustomizedContent.kt:36)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.components.CustomizedContentKt$CustomizedContent$1.invoke(CustomizedContent.kt:35)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.components.CustomizedContentKt.CustomizedContent(CustomizedContent.kt:29)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.lemmyui.PostCardKt.ExtendedPost-otr2n9U(PostCard.kt:601)
	at com.github.diegoberaldin.raccoonforlemmy.core.commonui.lemmyui.PostCardKt.PostCard(PostCard.kt:115)
	at com.github.diegoberaldin.raccoonforlemmy.unit.postdetail.PostDetailScreen$Content$6$1$1$3$1$1$1.invoke(PostDetailScreen.kt:837)
	at com.github.diegoberaldin.raccoonforlemmy.unit.postdetail.PostDetailScreen$Content$6$1$1$3$1$1$1.invoke(PostDetailScreen.kt:836)
```

which hints at some Markdown that is making the renderer freak out.

**Comment by diegoberaldin** [comment]
And here is the raw Markdown text of the post's body

```
## Shoutouts
Thanks to the following commenters below for additional recommendations that I added to this post!
- bruhduh
- Toes

---

## Free Open Source Alternatives

### [Visual/Graphical]
For all visual/graphical artists I would personally recommend switching from Photoshop over to
- [KDE's Krita](https://krita.org/en/)
  - Licensed under: [GPLv-3.0 or later](https://web.archive.org/web/20240606202428/https://invent.kde.org/graphics/krita/-/blob/master/COPYING)
  - [Flathub](https://flathub.org/apps/org.kde.krita)


[]()

- [GIMP](https://www.gimp.org/)
  - Licensed under: [GPLv-3.0 or later](https://web.archive.org/web/20240606200812/https://www.gimp.org/about/COPYING)
  - [Flathub](https://flathub.org/apps/org.gimp.GIMP)
---

### [Audio]
For audio migration I'd recommend switching from Soundbooth to
- [Tenacity](https://tenacityaudio.org/)
  - Licensed under: [GPLv-2.0 or later](https://web.archive.org/web/20240606201003/https://tenacityaudio.org/docs/index.html)
  - [Flathub](https://flathub.org/apps/org.tenacityaudio.Tenacity)

[]()

- [LMMS](https://lmms.io/)
  - Licensed under: [GPLv-2.0 or later](https://web.archive.org/web/20240607000234/https://docs.lmms.io/user-manual/8-legal/8.1-license)
  - [Flathub](https://flathub.org/apps/io.lmms.LMMS)
    - Status: "Unverified"
---

### [PDF]
Acrobat Reader to
- [MuPDF](https://mupdf.com/)
  - Licensed under: [AGPLv-3.0 or later](https://web.archive.org/web/20240606201218/https://mupdf.com/#licensing)
  - [F-Droid](https://f-droid.org/en/packages/com.artifex.mupdf.viewer.app/)

[]()

- [KDE's Okular](https://okular.kde.org/)
  - Licensed under: [GPLv-2.0 or later](https://web.archive.org/web/20240606201822/https://okular.kde.org/)
  - [Flathub](https://flathub.org/apps/org.kde.okular)
---

### [Video]
Premiere to
- [Shotcut](https://www.shotcut.org/)
  - Licensed under: [GPLv-3.0 or later](https://web.archive.org/web/20240512045234/https://github.com/mltframework/shotcut/blob/master/COPYING)
  - [Flathub](https://flathub.org/apps/org.shotcut.Shotcut)

[]()

- [Kdenlive](https://kdenlive.org/en/)
  - Licensed under: [GPLv-3.0 or later](https://web.archive.org/web/20240606234950/https://www.openshot.org/)
  - [Flathub](https://flathub.org/apps/org.kde.kdenlive)

[]()

- [OpenShot](https://www.openshot.org/)
  - Licensed under: [GPLv-3.0 only](https://web.archive.org/web/20240606234950/https://www.openshot.org/)
  - [Flathub](https://flathub.org/apps/org.openshot.OpenShot)
    - Status: "Unverified"

---

There's also an [excellent thread started by urska@lemmy.ca](https://lemmy.ca/post/22660638)
```

My take is that the empty links `[]()` are the culprit, I'll try adding a sanitization step for it before feeding that to the parser.

**Comment by diegoberaldin** [comment]
Yes I confirm it is exactly that the issue! Making a pull-request to fix immediately!
